enabled: true
data_remote: local-data
model_remote: local-models
data_targets:
  - data/raw.dvc
model_targets:
  - data/checkpoints.dvc
source_url: https://drive.google.com/file/d/1jIc-DDPGzVQOOhVJExGqBnhUQkVsro4Y/view?usp=drive_link
archive_path: data/raw/histopathologic-cancer-detection.zip
