enabled: true
data_remote: local-data
model_remote: local-models
data_targets:
  - data/raw.dvc
model_targets:
  - data/checkpoints.dvc
source_id: 1jIc-DDPGzVQOOhVJExGqBnhUQkVsro4Y
archive_path: data/raw/histopathologic-cancer-detection.zip
